### ISSUE TITLE
Discord Android app shows the revealed text inline, not hidden

### ISSUE THREAD

**Issue by Bluebie** [TimboKZ/discord-spoiler-bot#14]
<img width="291" alt="screen shot 2017-04-29 at 4 19 15 pm" src="https://cloud.githubusercontent.com/assets/12768/25553488/a78f24d8-2cf7-11e7-9d2c-931bc02b4b28.png">

Doesn't seem to work with android discord mobile app at all.

**Comment by TimboKZ** [comment]
Hi, Bluebie, thanks for opening this issue.

I don't have any Android devices so I've only found out about this bug today. After asking around, it appears Discord app for Android auto-plays all of the GIFs and since GIFs generated by my bot are meant to stop at the last frame, this ultimately reveals the spoiler.

Unfortunately, I can't really do much about it without ruining the experience on other platforms - I could potentially insert a blank frame in the end but this will break the spoilers in the desktop app.

The issue here is the inconsistent behaviour of GIFs on different platforms - they behave differently in iOS, Android and desktop apps. I've reported this issue to Discord devs but I don't think they'll be looking into this soon. At this point in time, there is nothing else I can do. Sorry.
