### ISSUE TITLE
Support Eris and Discordie

### ISSUE THREAD

**Issue by cryptiklemur** [TimboKZ/discord-spoiler-bot#7]

**Comment by TimboKZ** [comment]
While that is certainly a nice feature to have, I find it problematic to maintain compatibility with multiple Discord API wrappers. Could you tell me, what are the benefits you see in having the spoiler bot bootstrapped to an existing client over a brand new instance?

I'll be migrating the bot to Bluebird to make use of promises at some point in the future, which is when I can add support for custom clients. Basically, I was thinking of defining an interface for a wrapper object for Discord libraries so that people are not limited to discord.js and discord.io.

**Comment by TimboKZ** [comment]
Closing this for now - if anyone has anything to contribute to this discussion feel free to reopen the issue.
