### ISSUE TITLE
Works swimmingly on Windows but some errors on ubuntu

### ISSUE THREAD

**Issue by flantig** [TimboKZ/discord-spoiler-bot#8]
I was able to get your bot running on windows but for some reason I get this error message when I try installing it on Ubuntu. I followed all of the prerequisate steps (for some reason on that page the command they give does not install npm or node, that has to be done seperately). Running the code does succesfully create a discord-spoiler bot folder as well. Running the index.js gives me another error message different from what you see here but it also includes a lack of package.json. Which package.json is it asking for?

ownagecat@ownagecat-desktop:~/node_modules$ npm install discord-spoiler-bot --save

loadDep:gifencoder → reso ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine discord.js@11.0.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.2npm WARN saveError ENOENT: no such file or directory, open '/home/ownagecat/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ownagecat/package.json'
npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#master but none was installed.
npm WARN discord.js@11.0.0 requires a peer of node-opus@^0.2.0 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
npm WARN ownagecat No description
npm WARN ownagecat No repository field.
npm WARN ownagecat No README data
npm WARN ownagecat No license field.
ownagecat@ownagecat-desktop:~/node_modules$

**Comment by TimboKZ** [comment]
Number of issues I see with the output:
* What you're getting is a warning, the installation was still successful so you should be able to run the bot. See below for how to get rid of the warning.
* Are you sure you ran `npm init`? [package.json](https://docs.npmjs.com/files/package.json) should appear in the same directory where you execute `npm init`.
* It appears you're inside the `node_modules` directory, which is usually not the place you want to run the installation in. I suggest create a new folder, call it `spoiler-bot` or similar, and run `npm init` and `npm install ...` inside it.
* You'll need to upgrade your Node.js to v6+, as stated in the installation section. Otherwise the bot is likely to fail.

**Comment by flantig** [comment]
You're right, it was an outdated node.js. I had installed the wrong one.
I'm literally an idiot. You don't happen to have a donation button?

**Comment by TimboKZ** [comment]
Sadly, I don't. Thanks for the consideration though!
